on: pull_request
name: Pull Request Workflow
jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18,20,22]
    steps:
      - uses: actions/checkout@v4
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run build if cache
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: npm run build
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Execute tests
        run: npm run test
  automerge:
    runs-on: ubuntu-latest
    needs: runTests
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
          MERGE_LABELS: "dependencies"
  CodeQL-Build:
    runs-on: ubuntu-latest
    needs: runTests
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  OSSAR-Scan:
    runs-on: windows-latest
    needs: runTests
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Install .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: "3.1.201"
      - name: Run OSSAR
        uses: github/ossar-action@v1
        id: ossar
      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
