on:
  push:
    branches:
      - release
jobs:
  create-pr:
    name: Create PR on push to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'master'
          pr_title: 'Daily Release'
          pr_body: ':tada: *An automated PR*'
          pr_label: 'autorebase'
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
